### ISSUE TITLE
Useradd Doesn't Create Default Directory Structure

### ISSUE THREAD

**Issue by marshki** [marshki/plus_1#1]
`/etc/xdg/user-dirs.defaults` : contains info on default directory structure for `/home` when calling `useradd`, but this does not get created. Does it requires GUI login, or ...?

**Comment by piorekf** [comment]
`xdg` is a short for X Desktop Group. They are a group of people creating standards for interoperability between different Linux desktop managers (KDE, Gnome, Xfce, etc.). Therefore exerything with xdg in name is GUI related.

For the default content of a standard shell account home folder look into `/etc/skel`:
```$ ls -la /etc/skel/
total 24
drwxr-xr-x   3 root root 4096 Apr 22 01:55 ./
drwxr-xr-x 123 root root 4096 Jun 23 17:25 ../
-rw-r--r--   1 root root  127 Apr 22 01:55 .bash_logout
-rw-r--r--   1 root root  204 Apr 22 01:55 .bash_profile
-rw-r--r--   1 root root  551 Apr 22 01:55 .bashrc
drwx------   2 root root 4096 Aug 13  2018 .ssh/```

**Comment by marshki** [comment]
Took a look there, but on my test VMs I did not see an entry for the creation of directories such as: Desktop, Photos, etc. Any suggestions?

**Comment by piorekf** [comment]
Those home directories are not part of the standard UNIX/Linux account setup. They are a fancy add-on by the Desktop Managers so do not expect command line tools like `useradd` to care even a slightest bit about them and do not expect to see them in a typical (non GUI) server environment.

Either way this seems to answer your question: https://wiki.archlinux.org/index.php/XDG_user_directories

**Comment by marshki** [comment]
So we're back where we started...

**Comment by piorekf** [comment]
I'm not sure what you mean. Have you checked the URL which I pasted?
Something like this shouls do what you want:
```
if [[ ! -z $(which xdg-user-dirs-update) ]]
then
  su - ${username} -c "xdg-user-dirs-update"
  ### if you want to use sudo instead of su:
  # sudo -u ${username} -i xdg-user-dirs-update
fi
```

**Comment by marshki** [comment]
My initial link pointed to: `/etc/xdg/user-dirs.defaults`, so I was in the ball park; your link got me on base. Thanks for the suggestion!

**Comment by marshki** [comment]
username='sjobs'

    create_default_dirs () {

      if [[ -n $(command -v xdg-user-dirs-update) ]]
      then
      su ${username} -c xdg-user-dirs-update
      ### if you want to use sudo instead of su:
      # read -s -p "Enter sudo password: " passy
      # printf "%s" "$passy" |sudo -u $username -i xdg-user-dirs-update
      fi
    }

    create_default_dirs

**Comment by marshki** [comment]
Fixes issue. Need to test more thoroughly.
